### ISSUE TITLE
Version 1.6.0 - manage.py makemigrations creates a new migration

### ISSUE THREAD

**Issue by urievenchen** [revsys/django-friendship#76] opened 2018-06-27 21:20 UTC
manage.py makemigrations creates a new migration (with Django 1.11.13) which throws an exception when trying to migrate. Anyway manage.py makemigrations should not create new migrations. I'm downgrading to version 1.5.0.

**Comment by fcurella** [comment] 2018-07-03 15:33
dupe of #74

**Closed by fcurella** 2018-07-03 15:33 UTC

**Comment by urievenchen** [comment] 2018-07-04 18:19
Still not working in version 1.7.0.
